# Generated by Django 5.1.6 on 2025-02-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('RO', 'Romance'), ('BI', 'Biografia'), ('TE', 'Técnico'), ('FI', 'Ficção'), ('OU', 'Outros')], max_length=2)),
                ('capa', models.ImageField(blank=True, upload_to='biblioteca/capas/')),
            ],
        ),
    ]
